(function () {
  const sdk = (typeof window !== 'undefined' ? window.NodeGraphPluginSDK : null) ||
    (typeof self !== 'undefined' ? self.NodeGraphPluginSDK : null);
  if (!sdk || typeof sdk.createPluginRuntime !== 'function') {
    console.error('[PluginStarter] NodeGraphPluginSDK is not available.');
    return;
  }

  const runtime = sdk.createPluginRuntime({
    capabilities: {
      runtime: '__PLUGIN_ID__',
      version: '0.1.0'
    }
  });

  runtime.registerMethod('plugin:getInfo', async () => {
    const selection = await runtime.callHost('selection:get').catch(() => null);
    return {
      id: '__PLUGIN_ID__',
      version: '0.1.0',
      selection
    };
  });

  runtime.registerMethod('plugin:listNodes', () => [
    {
      type: '__PLUGIN_SLUG__-node',
      label: 'Starter Node',
      description: 'Generated by the NodeGraph plugin starter.',
      category: 'custom',
      icon: 'Extension'
    }
  ]);

  runtime.registerMethod('plugin:ping', () => '__PLUGIN_SLUG__-pong');
})();
